### ISSUE TITLE
 OPEN State integration

### ISSUE THREAD

**Issue by Abdylk** [OpenFuturePlatform/open-api#18]

**Comment by layko-andrey** [comment]
Wiki page creation issue #23

**Comment by Abdylk** [comment]
@trenatov @layko-andrey Please note that we need to implement this task in the following order: 
1. #24 Create Wiki page with Open State integration description 
2. #23 Create diagram for Open API and Open State integration
3. #20 RESTful API over OPEN State
4. #21 Authentication / Authorization
5. #18 Integration of OPEN API with OPEN State
6. #25 Remove the feature of OPEN State from OPEN API
7. #26 Reconfigure the CI CD pipeline.
@ruslanys Please confirm.

**Comment by ruslanys** [comment]
I believe the plan should go in the description of the task
