### ISSUE TITLE
Authentication / Authorization

### ISSUE THREAD

**Issue by Abdylk** [OpenFuturePlatform/open-api#21]
This task is the relates to #18 Epic.

**Comment by Abdylk** [comment]
@trenatov Please do the following things within this task. 
1. Write your implementation plan (support with diagram)
2. Submit the plan for review
3. Get it approved
4. Estimate
5. Implement logic according to the plan

**Comment by trenatov** [comment]
Closing this issue as it was decided to [secure Open State with firewall](https://github.com/OpenFuturePlatform/open-state/issues/29)
