### ISSUE TITLE
Create Wiki page with Open State integration description

### ISSUE THREAD

**Issue by layko-andrey** [OpenFuturePlatform/open-api#24]
Wiki page creation issue #23

_Originally posted by @layko-andrey in https://github.com/OpenFuturePlatform/open-api/issues/18#issuecomment-776126804_

**Comment by Abdylk** [comment]
@trenatov Please update us about the progress you have made on this task. Where we are at?! Thanks

**Comment by trenatov** [comment]
Created wiki page https://github.com/OpenFuturePlatform/open-api/wiki/Open-State-integration
